apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csv-pvc
  namespace: prod
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
